checkMode="interval"
intervalMinutes="120"
dailyHour="20"
dailyMinute="30"
weeklyDay="0"
weeklyHour="20"
weeklyMinute="30"
arch="true"
aur="true"
flatpak="false"
widgets="false"
fwupd="true"
feedsEnabled="false"
feedsFetchCount="3"
feeds="https://archlinux.org/feeds/news/"
middleAction="upgradeSystem"
rightAction=""
scrollUpAction="switchScheduler"
scrollDownAction="management"
notifyUpdates="true"
notifyUpdatesAction="false"
notifyEveryBump="true"
notifyNews="true"
notifyNewsAction="false"
notifyErrors="true"
notifySound="true"
notifyPersistent="false"
checkConn="false"
respectMeteredConn="false"
wrapper="yay"
archFlags=""
sudoBin="sudo"
rebootSystem="true"
mirrors="false"
mirrorsAge="7"
mirrorCount="5"
mirrorProgress="false"
dynamicUrl="null"
flatpakRemoveUnused="true"
flatpakFlags=""
widgetConfirmation="true"
restartShell="true"
restartCommand="systemctl --user restart plasma-plasmashell.service"
trayEnabledByDefault="false"
trayEnabledBy="undefined"
preExec=""
postExec=""
terminal="/usr/bin/konsole"
idleInhibit="true"
tmuxSession="false"
termFont="true"
mngHideFlatpak="false"
mngHideHeaders="false"
mngHideHelp="false"
mngHideNums="false"
fzfOptions=""
hideIconPolicy="0"
selectedIcon="apdatifier-plasmoid"
busyIndicator="spinner"
counterMode="badge"
counterBadgePosition="topRight"
counterSidePosition="left"
counterGapsInner="0"
counterGapsOuter="0"
counterOffsetX="0"
counterOffsetY="0"
counterColor=""
counterRadius="3"
counterOpacity="8"
pauseBadgePosition="topLeft"
updatedBadgePosition="topRight"
badgeOffsetX="0"
badgeOffsetY="0"
ownIconsUI="true"
autoHideScrollBar="true"
defaultTab="0"
switchDefaultTab="false"
sorting="true"
showStatusText="true"
showToolBar="true"
searchButton="true"
intervalButton="true"
sortButton="true"
viewButton="true"
managementButton="true"
upgradeButton="true"
checkButton="true"
pinButton="true"
settingsButton="true"
compactInfo="repository"
extendedShowRepository="true"
extendedShowInstallReason="true"
highlightVersionDiff="false"
colorizeInstallReason="false"
tabBarVisible="true"
tabBarTexts="true"
version="v2.9.9"
configMsg="true"
dbPath="${TMPDIR:-/tmp}/checkup-db-$(id -u)"

